/* eslint-disable */
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/SkyRoc1/skyroc-router

import type { RouteFileKey, RouteLayoutKey, RawRouteComponent } from "@skyroc-router/types";
import HomeLoading from "@/pages/(base)/home/loading.tsx";
export const layouts: Record<RouteFileKey, RawRouteComponent> = {
  HomeLayout: () => import("@/pages/(base)/home/layout.tsx"),
};

export const views: Record<RouteFileKey, RawRouteComponent> = {
  About: () => import("@/pages/about/index.tsx"),
  AboutDetail: () => import("@/pages/about/detail/index.tsx"),
  AboutDetailId: () => import("@/pages/about/detail/[id].tsx"),
  AboutDetailIdUserId: () => import("@/pages/about/detail_[id]_[userId].tsx"),
  AboutDetailProjectPid: () => import("@/pages/about/detail/project/[pid].tsx"),
  Home: () => import("@/pages/(base)/home/index.tsx"),
  HomeNotFound: () => import("@/pages/(base)/home/[...all].tsx"),
  ProjectPid: () => import("@/pages/project/[pid]/index.tsx"),
  ProjectPidEditId: () => import("@/pages/project/[pid]/edit/[id].tsx"),
};

export const errors: Record<RouteFileKey, RawRouteComponent> = {
  HomeError: () => import("@/pages/(base)/home/error.tsx"),
};

export const loadings: Record<RouteFileKey, RawRouteComponent> = {
  HomeLoading,
};
