/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/SkyRoc1/skyroc-router

export {}

declare module "react-router/auto-routes" {
  type RouteNamedMap = import("react-router/auto-routes").RouteNamedMap;

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap;
  }
}

declare module "react-router/auto-routes" {
  import type { RouteParamsRawGeneric, RouteParamsGeneric, RouteMeta, RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from "react-router/auto-routes";

  /**
   * route named map
  */
  export interface RouteNamedMap {
    "Root": RouteRecordInfo<"Root", "/", Record<never, never>, Record<never, never>>;
    "NotFound": RouteRecordInfo<"NotFound", "*", Record<never, never>, Record<never, never>>;
    "About": RouteRecordInfo<"About", "/about", Record<never, never>, Record<never, never>>;
    "AboutDetail": RouteRecordInfo<"AboutDetail", "/about/detail", Record<never, never>, Record<never, never>>;
    "AboutDetailId": RouteRecordInfo<"AboutDetailId", "/about/detail/:id", { id: ParamValue<true> }, { id: ParamValue<false> }>;
    "AboutDetailIdUserId": RouteRecordInfo<"AboutDetailIdUserId", "/about/detail/:id/:userId", { id: ParamValue<true>, userId: ParamValue<true> }, { id: ParamValue<false>, userId: ParamValue<false> }>;
    "AboutDetailProjectPid": RouteRecordInfo<"AboutDetailProjectPid", "/about/detail/project/:pid", { pid: ParamValue<true> }, { pid: ParamValue<false> }>;
    "Home": RouteRecordInfo<"Home", "/home", Record<never, never>, Record<never, never>>;
    "HomeError": RouteRecordInfo<"HomeError", "/home/error", Record<never, never>, Record<never, never>>;
    "HomeLayout": RouteRecordInfo<"HomeLayout", "/home/layout", Record<never, never>, Record<never, never>>;
    "HomeLoading": RouteRecordInfo<"HomeLoading", "/home/loading", Record<never, never>, Record<never, never>>;
    "HomeNotFound": RouteRecordInfo<"HomeNotFound", "/home/*", Record<never, never>, Record<never, never>>;
    "ProjectPid": RouteRecordInfo<"ProjectPid", "/project/:pid", { pid: ParamValue<true> }, { pid: ParamValue<false> }>;
    "ProjectPidEditId": RouteRecordInfo<"ProjectPidEditId", "/project/:pid/edit/:id", { pid: ParamValue<true>, id: ParamValue<true> }, { pid: ParamValue<false>, id: ParamValue<false> }>
  }
}
